name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - uses: actions/cache@v4
        name: Setup cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-cache-${{ hashFiles('**/bun.lockb') }}

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: pnpm run lint
        run: pnpm run lint

      - name: pnpm run typecheck
        run: pnpm run typecheck
